# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2021-02-08 21:16:38 krylon>
#
#+TAGS: optimize(o) refactor(r) bug(b) feature(f) architecture(a)
#+TODO: TODO(t) IMPLEMENT(i) TEST(e) RESEARCH(r) | DONE(d)
#+TODO: MEDITATE(m) PLANNING(p) | FAILED(f) CANCELLED(c) SUSPENDED(s)
#+PRIORITIES: A G D

* Ticker
  Ticker is an RSS/Atom reader with a builtin archive and web interface.
  It supports tagging news items, and rating news items, with a bayesian
  classifier to automatically suggest ratings, as well as filtering news items
  based on suggested ratings.
** Clocktable
   #+BEGIN: clocktable :scope file :maxlevel 20
   #+CAPTION: Clock summary at [2021-02-08 Mo 21:16]
   | Headline             | Time      |         |       |
   |----------------------+-----------+---------+-------|
   | *Total time*         | *1d 9:34* |         |       |
   |----------------------+-----------+---------+-------|
   | Ticker               | 1d 9:34   |         |       |
   | \_  Components [2/2] |           | 1d 9:34 |       |
   | \_    Feed [2/2]     |           |         |  3:16 |
   | \_    Database [0/0] |           |         | 18:01 |
   | \_    Reader [0/0]   |           |         | 12:17 |
   #+END:

** Questions
** Components [2/2]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: children
  :END:
*** Feed [2/2]
    :LOGBOOK:
    CLOCK: [2021-02-06 Sa 17:57]--[2021-02-06 Sa 18:47] =>  0:50
    CLOCK: [2021-02-05 Fr 20:57]--[2021-02-05 Fr 21:57] =>  1:00
    CLOCK: [2021-02-01 Mo 15:27]--[2021-02-01 Mo 16:29] =>  1:02
    CLOCK: [2021-02-01 Mo 12:46]--[2021-02-01 Mo 13:10] =>  0:24
    :END:
**** CANCELLED URL
     CLOSED: [2021-02-05 Fr 20:57]
     Is there an advantage to representing the URL as a *net.URL object?
**** DONE Fetching
     CLOSED: [2021-02-05 Fr 20:57]
*** Database [0/0]
    :LOGBOOK:
    CLOCK: [2021-02-05 Fr 13:15]--[2021-02-05 Fr 17:23] =>  4:08
    CLOCK: [2021-02-04 Do 18:55]--[2021-02-04 Do 20:30] =>  1:35
    CLOCK: [2021-02-04 Do 18:05]--[2021-02-04 Do 18:37] =>  0:32
    CLOCK: [2021-02-04 Do 12:47]--[2021-02-04 Do 13:52] =>  1:05
    CLOCK: [2021-02-04 Do 09:18]--[2021-02-04 Do 10:03] =>  0:45
    CLOCK: [2021-02-03 Mi 19:24]--[2021-02-03 Mi 23:04] =>  3:40
    CLOCK: [2021-02-02 Di 18:50]--[2021-02-02 Di 20:50] =>  2:00
    CLOCK: [2021-02-02 Di 07:53]--[2021-02-02 Di 07:59] =>  0:06
    CLOCK: [2021-02-01 Mo 16:30]--[2021-02-01 Mo 20:40] =>  4:10
    :END:
    Is there any reason /not/ to use good old SQLite?
    I don't think so.
*** Reader [0/0]
    :LOGBOOK:
    CLOCK: [2021-02-08 Mo 20:33]--[2021-02-08 Mo 21:16] =>  0:43
    CLOCK: [2021-02-08 Mo 19:25]--[2021-02-08 Mo 19:51] =>  0:26
    CLOCK: [2021-02-08 Mo 12:58]--[2021-02-08 Mo 15:36] =>  2:38
    CLOCK: [2021-02-07 So 17:45]--[2021-02-07 So 22:15] =>  4:30
    CLOCK: [2021-02-07 So 11:46]--[2021-02-07 So 15:46] =>  4:00
    :END:
*** Web interface
** Tedious tasks
