# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2021-02-04 18:37:17 krylon>
#
#+TAGS: optimize(o) refactor(r) bug(b) feature(f) architecture(a)
#+TODO: TODO(t) IMPLEMENT(i) TEST(e) RESEARCH(r) | DONE(d)
#+TODO: MEDITATE(m) PLANNING(p) | FAILED(f) CANCELLED(c) SUSPENDED(s)
#+PRIORITIES: A G D

* Ticker
  Ticker is an RSS/Atom reader with a builtin archive and web interface.
  It supports tagging news items, and rating news items, with a bayesian
  classifier to automatically suggest ratings, as well as filtering news items
  based on suggested ratings.
** Clocktable
   #+BEGIN: clocktable :scope file :maxlevel 20
   #+CAPTION: Clock summary at [2021-02-04 Do 18:37]
   | Headline             | Time    |       |       |
   |----------------------+---------+-------+-------|
   | *Total time*         | *13:44* |       |       |
   |----------------------+---------+-------+-------|
   | Ticker               | 13:44   |       |       |
   | \_  Components [0/2] |         | 13:44 |       |
   | \_    Feed [0/2]     |         |       |  1:26 |
   | \_    Database [0/0] |         |       | 12:18 |
   #+END:

** Questions
** Components [0/2]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: children
  :END:
*** Feed [0/2]
    :LOGBOOK:
    CLOCK: [2021-02-01 Mo 15:27]--[2021-02-01 Mo 16:29] =>  1:02
    CLOCK: [2021-02-01 Mo 12:46]--[2021-02-01 Mo 13:10] =>  0:24
    :END:
**** MEDITATE URL
     Is there an advantage to representing the URL as a *net.URL object?
**** TODO Fetching
*** Database [0/0]
    :LOGBOOK:
    CLOCK: [2021-02-04 Do 18:05]--[2021-02-04 Do 18:37] =>  0:32
    CLOCK: [2021-02-04 Do 12:47]--[2021-02-04 Do 13:52] =>  1:05
    CLOCK: [2021-02-04 Do 09:18]--[2021-02-04 Do 10:03] =>  0:45
    CLOCK: [2021-02-03 Mi 19:24]--[2021-02-03 Mi 23:04] =>  3:40
    CLOCK: [2021-02-02 Di 18:50]--[2021-02-02 Di 20:50] =>  2:00
    CLOCK: [2021-02-02 Di 07:53]--[2021-02-02 Di 07:59] =>  0:06
    CLOCK: [2021-02-01 Mo 16:30]--[2021-02-01 Mo 20:40] =>  4:10
    :END:
    Is there any reason /not/ to use good old SQLite?
    I don't think so.
*** Web interface
** Tedious tasks
